dist: bionic
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ bionic multiverse" 
  - sudo apt-get update
  - sudo apt-get install -y git python3 python3-pip python3-selenium firefox firefoxdriver python3-opencv xvfb

# command to run tests
script:
#- pytest tests
  - pycodestyle --ignore=E402 *.py
