# Generated by Django 2.1.4 on 2018-12-05 16:35

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(verbose_name='identifier')),
                ('name', models.TextField(verbose_name='name')),
                ('abbreviation', models.TextField(verbose_name='abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(verbose_name='identifier')),
                ('language', models.TextField(verbose_name='language')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transcriptions.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_corpus', models.IntegerField(verbose_name='position_in_corpus')),
                ('total_chapters', models.IntegerField(verbose_name='chapter_total')),
                ('verses_per_chapter', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='verses_per_chapter')),
                ('abbreviation', models.TextField(verbose_name='abbreviation')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(unique=True, verbose_name='identifier')),
                ('document_id', models.CharField(max_length=25, verbose_name='document_id')),
                ('tei', models.TextField(verbose_name='tei')),
                ('source', models.TextField(verbose_name='source')),
                ('siglum', models.CharField(max_length=25, verbose_name='siglum')),
                ('document_type', models.TextField(verbose_name='document_type')),
                ('language', models.CharField(max_length=5, verbose_name='language')),
                ('corrector_order', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('total_verses', models.IntegerField(verbose_name='total_verses')),
                ('total_unique_verses', models.IntegerField(verbose_name='total_verses')),
                ('loading_complete', models.NullBooleanField(verbose_name='loading_complete')),
                ('public', models.BooleanField(verbose_name='public')),
                ('corpus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transcriptions.Corpus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(verbose_name='identifier')),
                ('index', models.IntegerField(verbose_name='index')),
                ('document_id', models.CharField(max_length=25, verbose_name='document_id')),
                ('tei', models.TextField(verbose_name='tei')),
                ('context', models.TextField(verbose_name='context')),
                ('reference', models.TextField(verbose_name='reference')),
                ('chapter_number', models.IntegerField(null=True, verbose_name='chapter_number')),
                ('verse_number', models.IntegerField(null=True, verbose_name='verse_number')),
                ('siglum', models.CharField(max_length=25, verbose_name='siglum')),
                ('document_type', models.TextField(verbose_name='document_type')),
                ('language', models.CharField(max_length=5, verbose_name='language')),
                ('duplicate_position', models.IntegerField(null=True, verbose_name='duplicate_position')),
                ('lection', models.TextField(verbose_name='lection')),
                ('transcription_siglum', models.TextField(verbose_name='transcription_siglum')),
                ('transcription_identifier', models.TextField(verbose_name='transcription_identifier')),
                ('inscriptio', models.NullBooleanField(verbose_name='inscriptio')),
                ('subscriptio', models.NullBooleanField(verbose_name='subscriptio')),
                ('witnesses', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('public', models.BooleanField(verbose_name='public')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='transcriptions.Transcription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['work__sort_value', 'chapter_number', 'verse_number'],
            },
        ),
        migrations.CreateModel(
            name='VerseReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.TextField()),
                ('hand_abbreviation', models.TextField()),
                ('reading_text', models.TextField()),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_readings', to='transcriptions.Verse')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(verbose_name='identifier')),
                ('name', models.TextField(verbose_name='name')),
                ('sort_value', models.IntegerField(verbose_name='sort_value')),
                ('abbreviation', models.TextField(verbose_name='abbreviation')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='transcriptions.Collection')),
            ],
            options={
                'ordering': ['sort_value'],
            },
        ),
        migrations.AddField(
            model_name='verse',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verse_details', to='transcriptions.Work'),
        ),
        migrations.AddField(
            model_name='transcription',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcriptions', to='transcriptions.Work'),
        ),
        migrations.AddField(
            model_name='structure',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcriptions.Work'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='works',
            field=models.ManyToManyField(through='transcriptions.Structure', to='transcriptions.Work'),
        ),
    ]
